### ISSUE TITLE
to create readme for cognito

### ISSUE THREAD

**Issue by yuki5155** [yuki5155/go-aws#12]

**Comment by yuki5155** [comment]
would you create the readme how to use cognito golang script

```golang:cognito.go
package cognito

import (
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	"github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider/types"
)

type TokenResponse struct {
	AccessToken  string `json:"access_token"`
	IdToken      string `json:"id_token"`
	RefreshToken string `json:"refresh_token"`
	TokenType    string `json:"token_type"`
	ExpiresIn    int    `json:"expires_in"`
}

type CognitoConfig struct {
	Domain       string
	Region       string
	ClientID     string
	ClientSecret string
	UserPoolID   string // Optional, will be derived if not provided
}

// JWTClaims represents standard JWT claims plus any custom fields
type JWTClaims map[string]interface{}

// GetTokens exchanges authorization code for tokens
func GetTokens(code, redirectURI string, config CognitoConfig) (*TokenResponse, error) {
	tokenEndpoint := fmt.Sprintf("https://%s.auth.%s.amazoncognito.com/oauth2/token",
		config.Domain, config.Region)

	data := url.Values{}
	data.Set("grant_type", "authorization_code")
	data.Set("client_id", config.ClientID)
	data.Set("code", code)
	data.Set("redirect_uri", redirectURI)

	req, err := http.NewRequest("POST", tokenEndpoint, strings.NewReader(data.Encode()))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	if config.ClientSecret != "" {
		req.SetBasicAuth(config.ClientID, config.ClientSecret)
	}

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("token request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("failed to get token: status code %s", resp.Status)
	}

	var tokenResp TokenResponse
	if err := json.NewDecoder(resp.Body).Decode(&tokenResp); err != nil {
		return nil, fmt.Errorf("failed to parse token response: %w", err)
	}

	return &tokenResp, nil
}

// ValidateIDToken validates the ID token and returns claims if valid
func ValidateIDToken(idToken string, config CognitoConfig) (bool, JWTClaims, error) {
	// Parse JWT token manually (no external dependencies)
	parts := strings.Split(idToken, ".")
	if len(parts) != 3 {
		return false, nil, fmt.Errorf("invalid token format")
	}

	// Decode claims
	claimsJSON, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return false, nil, fmt.Errorf("failed to decode token payload: %w", err)
	}

	var claims JWTClaims
	if err := json.Unmarshal(claimsJSON, &claims); err != nil {
		return false, nil, fmt.Errorf("failed to parse token claims: %w", err)
	}

	// Get token issuer
	issuer, _ := claims["iss"].(string)
	if issuer == "" {
		return false, nil, fmt.Errorf("missing issuer claim")
	}

	// Check expiration
	exp, ok := claims["exp"].(float64)
	if !ok {
		return false, nil, fmt.Errorf("invalid expiration claim")
	}

	if time.Now().Unix() > int64(exp) {
		return false, claims, fmt.Errorf("token expired")
	}

	// Determine user pool ID if not provided
	userPoolID := config.UserPoolID
	if userPoolID == "" && strings.Contains(issuer, "cognito-idp") {
		parts := strings.Split(issuer, "/")
		if len(parts) > 0 {
			userPoolID = parts[len(parts)-1]
		}
	}

	// For Google federated auth
	if strings.HasPrefix(issuer, "https://accounts.google.com") {
		// For a real implementation, verify Google token signature
		// This simplified version only checks expiration (done above)
		return true, claims, nil
	}

	// For Cognito tokens
	if userPoolID == "" {
		return false, nil, fmt.Errorf("could not determine user pool ID")
	}

	// For ID tokens, we need to use AdminGetUser or GetUser
	// Use the 'sub' claim to identify the user
	sub, _ := claims["sub"].(string)
	if sub == "" {
		return false, claims, fmt.Errorf("missing subject claim")
	}

	// When using the SDK for full validation (not in this simplified version):
	// cfg, err := createAWSConfig(config.Region)
	// if err != nil {
	//     return false, claims, err
	// }
	// cognitoClient := cognitoidentityprovider.NewFromConfig(cfg)
	// Then call AdminGetUser or similar APIs

	// Try to validate using GetUser if we have an access token
	// For ID tokens, this is a minimal validation
	audience, _ := claims["aud"].(string)
	if audience != config.ClientID {
		return false, claims, fmt.Errorf("invalid audience")
	}

	return true, claims, nil
}

// GetUserAttributes retrieves user attributes using the access token
func GetUserAttributes(accessToken string, config CognitoConfig, awsConf aws.Config) (map[string]string, error) {

	cognitoClient := cognitoidentityprovider.NewFromConfig(awsConf)
	input := &cognitoidentityprovider.GetUserInput{
		AccessToken: aws.String(accessToken),
	}

	result, err := cognitoClient.GetUser(context.Background(), input)
	if err != nil {
		return nil, fmt.Errorf("failed to get user attributes: %w", err)
	}

	attributes := make(map[string]string)
	for _, attr := range result.UserAttributes {
		attributes[aws.ToString(attr.Name)] = aws.ToString(attr.Value)
	}

	return attributes, nil
}

// RefreshTokens refreshes the access and ID tokens using a refresh token
func RefreshTokens(refreshToken string, cognitoConfig CognitoConfig) (*TokenResponse, error) {
	// Create AWS config with just region, no custom endpoint resolver
	awsCfg, err := config.LoadDefaultConfig(context.Background(),
		config.WithRegion(cognitoConfig.Region),
	)
	if err != nil {
		return nil, err
	}

	cognitoClient := cognitoidentityprovider.NewFromConfig(awsCfg)

	// Use string literal for auth flow to match AWS enum exactly
	input := &cognitoidentityprovider.InitiateAuthInput{
		AuthFlow: types.AuthFlowTypeRefreshTokenAuth,
		ClientId: aws.String(cognitoConfig.ClientID),
		AuthParameters: map[string]string{
			"REFRESH_TOKEN": refreshToken,
		},
	}

	if cognitoConfig.ClientSecret != "" {
		input.AuthParameters["SECRET_HASH"] = computeSecretHash(cognitoConfig.ClientID, cognitoConfig.ClientSecret, refreshToken)
	}

	result, err := cognitoClient.InitiateAuth(context.Background(), input)
	if err != nil {
		return nil, fmt.Errorf("failed to refresh token: %w", err)
	}

	response := &TokenResponse{
		AccessToken:  aws.ToString(result.AuthenticationResult.AccessToken),
		IdToken:      aws.ToString(result.AuthenticationResult.IdToken),
		RefreshToken: aws.ToString(result.AuthenticationResult.RefreshToken),
		ExpiresIn:    int(result.AuthenticationResult.ExpiresIn),
		TokenType:    aws.ToString(result.AuthenticationResult.TokenType),
	}

	// If refresh token wasn't returned (common), use the one we already have
	if response.RefreshToken == "" {
		response.RefreshToken = refreshToken
	}

	return response, nil
}

// Helper function to compute secret hash for client secret validation
// In a real implementation, you would use HMAC-SHA256
func computeSecretHash(clientID, clientSecret, username string) string {
	// The format is: SHA256(client_secret + username + client_id)
	mac := hmac.New(sha256.New, []byte(clientSecret))
	mac.Write([]byte(username + clientID))
	return base64.StdEncoding.EncodeToString(mac.Sum(nil))
}

```

```golang:cognito_test.go
package cognito

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"strings"
	"testing"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
)

func loadEnv(filename string) error {
	file, err := os.Open(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "#") || len(strings.TrimSpace(line)) == 0 {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			key := strings.TrimSpace(parts[0])
			value := strings.TrimSpace(parts[1])
			os.Setenv(key, value)
		}
	}

	return scanner.Err()
}

// Helper function to create AWS configuration
func createAWSConfig(region string) (aws.Config, error) {
	return config.LoadDefaultConfig(context.Background(),
		config.WithRegion(region),
		config.WithEndpointResolverWithOptions(aws.EndpointResolverWithOptionsFunc(
			func(service, region string, options ...interface{}) (aws.Endpoint, error) {
				// Normalize service name to lowercase
				serviceLower := strings.ToLower(service)

				// Handle Cognito Identity Provider specifically
				if serviceLower == "cognito-idp" ||
					serviceLower == "cognitoidentityprovider" ||
					strings.Contains(serviceLower, "cognito") {
					return aws.Endpoint{
						URL: fmt.Sprintf("https://cognito-idp.%s.amazonaws.com", region),
					}, nil
				}

				// For any other AWS service
				return aws.Endpoint{
					URL: fmt.Sprintf("https://%s.%s.amazonaws.com", serviceLower, region),
				}, nil
			},
		)),
	)
}

func TestGetTokensAndVerify(t *testing.T) {
	// Load environment variables
	if err := loadEnv("../.env"); err != nil {
		t.Fatal(err)
	}

	region := "ap-northeast-1"
	if os.Getenv("AWS_REGION") != "" {
		region = os.Getenv("AWS_REGION")
	}

	// Create config with real AWS - ensure no LocalStack endpoint is used
	cfg, err := config.LoadDefaultConfig(context.TODO(),
		config.WithRegion(region),
	)
	if err != nil {
		t.Fatalf("unable to load SDK config: %v", err)
	}

	// Remove any AWS_ENDPOINT_URL environment variable if it exists
	// This ensures we're not using LocalStack
	os.Unsetenv("AWS_ENDPOINT_URL")

	// Print credentials for debugging
	creds, err := cfg.Credentials.Retrieve(context.TODO())
	if err == nil {
		t.Logf("Using AWS credentials: %s", creds.AccessKeyID)
	}

	// Create regular Cognito config
	config := CognitoConfig{
		Domain:       os.Getenv("COGNITO_DOMAIN"),
		Region:       region,
		ClientID:     os.Getenv("COGNITO_CLIENT_ID"),
		ClientSecret: os.Getenv("COGNITO_CLIENT_SECRET"),
		UserPoolID:   os.Getenv("COGNITO_USER_POOL_ID"),
	}
	callBackURL := os.Getenv("COGNITO_CALLBACK_URL")
	authCode := os.Getenv("COGNITO_AUTH_CODE")

	// Step 1: Get tokens
	tokens, err := GetTokens(authCode, callBackURL, config)
	if err != nil {
		t.Fatal(err)
	}
	fmt.Println("Tokens obtained successfully")
	fmt.Printf("Access Token: %s...\n", tokens.AccessToken[:30])
	fmt.Printf("ID Token: %s...\n", tokens.IdToken[:30])
	fmt.Printf("Refresh Token: %s...\n", tokens.RefreshToken[:30])

	// Step 2: Verify ID token
	isValid, claims, err := ValidateIDToken(tokens.IdToken, config)
	if err != nil {
		t.Logf("Token validation error (might be expected for expired tokens): %v", err)
	}

	fmt.Printf("Token valid: %v\n", isValid)
	if claims != nil {
		fmt.Println("\nToken claims:")
		// Print important claims
		if sub, ok := claims["sub"].(string); ok {
			fmt.Printf("Subject (sub): %s\n", sub)
		}
		if email, ok := claims["email"].(string); ok {
			fmt.Printf("Email: %s\n", email)
		}
		if name, ok := claims["name"].(string); ok {
			fmt.Printf("Name: %s\n", name)
		}
		if exp, ok := claims["exp"].(float64); ok {
			fmt.Printf("Expiration: %v\n", exp)
		}
		if iat, ok := claims["iat"].(float64); ok {
			fmt.Printf("Issued At: %v\n", iat)
		}
	}

	// Step 3: Get user attributes using direct client
	t.Run("GetUserAttributes", func(t *testing.T) {
		// Create a client directly without custom resolver
		client := cognitoidentityprovider.NewFromConfig(cfg)

		input := &cognitoidentityprovider.GetUserInput{
			AccessToken: aws.String(tokens.AccessToken),
		}

		result, err := client.GetUser(context.TODO(), input)
		if err != nil {
			t.Logf("Error getting user attributes directly: %v", err)
			t.Skip("Skipping attributes test due to API error")
			return
		}

		fmt.Println("\nUser attributes:")
		for _, attr := range result.UserAttributes {
			fmt.Printf("%s: %s\n", aws.ToString(attr.Name), aws.ToString(attr.Value))
		}
	})

	// Step 4: Refresh token using the RefreshTokens function from the package
	if tokens.RefreshToken != "" {
		t.Run("RefreshToken", func(t *testing.T) {
			refreshedTokens, err := RefreshTokens(tokens.RefreshToken, config)
			if err != nil {
				t.Fatalf("Error refreshing token: %v", err)
			}

			fmt.Println("\nTokens refreshed successfully")
			fmt.Printf("New Access Token: %s...\n", refreshedTokens.AccessToken[:30])
			fmt.Printf("New ID Token: %s...\n", refreshedTokens.IdToken[:30])

			// Verify the new token is valid
			isValid, newClaims, err := ValidateIDToken(refreshedTokens.IdToken, config)
			if err != nil {
				t.Logf("New token validation error: %v", err)
			}
			fmt.Printf("New token valid: %v\n", isValid)

			// Check expiration of new token
			if exp, ok := newClaims["exp"].(float64); ok {
				fmt.Printf("New token expiration: %v\n", exp)
			}
		})
	}
}

```

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool and Identity Pool with Google Authentication

Parameters:
  UserPoolName:
    Type: String
    Default: MyCognitoUserPool
    Description: Name of the Cognito User Pool
  
  IdentityPoolName:
    Type: String
    Default: MyCognitoIdentityPool
    Description: Name of the Cognito Identity Pool
  
  CognitoDomainPrefix:
    Type: String
    Description: Prefix for your Cognito domain (must be globally unique, only lowercase alphanumeric)
    AllowedPattern: '^[a-z0-9]{3,63}$'
    ConstraintDescription: Domain prefix must contain 3-63 lowercase alphanumeric characters
  
  CallbackURL:
    Type: String
    Default: https://example.com/callback
    Description: Callback URL after login
  
  LogoutURL:
    Type: String
    Default: https://example.com/logout
    Description: Logout URL
  
  GoogleClientId:
    Type: String
    Description: Google OAuth Client ID
    NoEcho: true
  
  GoogleClientSecret:
    Type: String
    Description: Google OAuth Client Secret
    NoEcho: true

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: false

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    DependsOn: CognitoUserPool
    Properties:
      Domain: !Ref CognitoDomainPrefix
      UserPoolId: !Ref CognitoUserPool

  UserPoolIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    DependsOn: CognitoUserPool
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleClientSecret
        authorize_scopes: email profile openid
      AttributeMapping:
        email: email
        name: name
        given_name: given_name
        family_name: family_name
        picture: picture

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: 
      - CognitoUserPool
      - UserPoolIdentityProvider
    Properties:
      ClientName: UserPoolClient
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - COGNITO # googleのみにしたい場合はここをコメントアウト
        - Google
      CallbackURLs:
        - !Ref CallbackURL
      LogoutURLs:
        - !Ref LogoutURL
      PreventUserExistenceErrors: ENABLED

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    DependsOn: CognitoUserPoolClient
    Properties:
      IdentityPoolName: !Ref IdentityPoolName
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClient
          ProviderName: !Sub cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}
          ServerSideTokenCheck: true

  CognitoAuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: AuthenticatedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'cognito-sync:*'
                  - 'cognito-identity:*'
                  - 'execute-api:Invoke'
                Resource: '*'

  CognitoUnauthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': unauthenticated
      Policies:
        - PolicyName: UnauthenticatedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'cognito-sync:*'
                Resource: '*'

  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    DependsOn: 
      - CognitoIdentityPool
      - CognitoAuthenticatedRole
      - CognitoUnauthenticatedRole
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthenticatedRole.Arn
        unauthenticated: !GetAtt CognitoUnauthenticatedRole.Arn

Outputs:
  UserPoolId:
    Value: !Ref CognitoUserPool
    Description: User Pool ID
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolId

  UserPoolClientId:
    Value: !Ref CognitoUserPoolClient
    Description: User Pool Client ID
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolClientId

  IdentityPoolId:
    Value: !Ref CognitoIdentityPool
    Description: Identity Pool ID
    Export:
      Name: !Sub ${AWS::StackName}-IdentityPoolId

  UserPoolDomain:
    Value: !Sub https://${CognitoDomainPrefix}.auth.${AWS::Region}.amazoncognito.com
    Description: Hosted UI Domain
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolDomain

  HostedUIURL:
    Value: !Sub https://${CognitoDomainPrefix}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${CognitoUserPoolClient}&response_type=code&redirect_uri=${CallbackURL}
    Description: Complete Hosted UI Login URL

  GoogleRedirectURI:
    Value: !Sub https://${CognitoDomainPrefix}.auth.${AWS::Region}.amazoncognito.com/oauth2/idpresponse
    Description: Redirect URI to add in Google Cloud Console Authorized redirect URIs
  
  JavaScriptOrigins:
    Value: !Sub https://${CognitoDomainPrefix}.auth.${AWS::Region}.amazoncognito.com
    Description: JavaScript origins to add in Google Cloud Console Authorized JavaScript origins

  LogoutEndpoint:
    Value: !Sub https://${CognitoDomainPrefix}.auth.${AWS::Region}.amazoncognito.com/logout?client_id=${CognitoUserPoolClient}&logout_uri=${LogoutURL}
    Description: Complete Logout URL
```
